#!/usr/bin/env bash

bindirs=`echo $PATH | tr ':' '\n'`

binfiles=""

for directory in $bindirs; do
    if [ "$(ls -A $directory)" ]
    then
        binfiles="$binfiles $(ls -tdQ $directory/* | xargs | tr ' ' '\n')"
    fi
done

executable=`printf '%s\n' $binfiles | fzf`

nohup $executable &> /dev/null &disown

sleep 0
